# Generated by Django 3.2.8 on 2021-10-29 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Businesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('tax_id', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
